### PR TITLE
[Fixes #9 & #14] Update Styling on De-id Config Form

### LINKED ISSUE #9: Standardize the fonts
The app seems to use at least three type of fonts. We should settle on one, maximum two.

image

### LINKED ISSUE #14: Enlarge Masking Char Field / Other Text Fields

### PR DESCRIPTION
**Pull request by boyleconnor**
In addition to the mentioned issues, this addresses nlpsandbox/phi-deidentifier#36

### CODE REVIEW

**Comment by tschaffter** [comment]
For PR that update a style issue, posting a screenshot of the new look is appreciated.

I cloned the branch and here is what I obtained:

image

The font in the orange rectangle is still different from the rest of the app.

**Comment by cascadianblue** [comment]
@tschaffter that's not what it should look like. You might have to re-build the container? Here is what the layout is supposed to look like now:

New UI

**Comment by cascadianblue** [comment]
Detail view of `Steps` section

Steps Focus View

**Review by tschaffter — APPROVED** [review]
This PR looks great! 🚀

**Pull request merged**
